In [87]:
#Import the necessary packages
import pandas as pd
import numpy as np

In [88]:
#import and load the dataset
df = pd.read_excel("C:\\Users\\User\\Desktop\\Python files\\Customer Call List.xlsx")
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

# EDA

In [23]:
df.shape

(21, 8)

In [24]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [25]:
categorical_cols = df.select_dtypes(include='object').columns
categorical_cols

Index(['First_Name', 'Last_Name', 'Phone_Number', 'Address', 'Paying Customer',
       'Do_Not_Contact'],
      dtype='object')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

#

# DESCRIPTIVE STATISTICS

In [40]:
df.describe().T

            count    mean      std     min      25%     50%      75%     max
CustomerID   20.0  1010.5  5.91608  1001.0  1005.75  1010.5  1015.25  1020.0

# DATA CLEANING

### dealing with missing values

In [73]:
# what is the distribution of missing values per column?
df.isna().sum()

CustomerID           0
First_Name           0
Last_Name            0
Phone_Number         0
Address              0
Paying Customer      0
Do_Not_Contact       0
Not_Useful_Column    0
dtype: int64

In [74]:
# Better yet, let's view the proportion of missing values per column
(df.isna().mean()*100).round().sort_values(ascending= False)

CustomerID           0.0
First_Name           0.0
Last_Name            0.0
Phone_Number         0.0
Address              0.0
Paying Customer      0.0
Do_Not_Contact       0.0
Not_Useful_Column    0.0
dtype: float64

In [75]:
# FILLING MISSING VALUES

#df = df.dropna()# Drop Rows with Missing Values
#df = df.dropna(subset=['Do_Not_Contact', 'Phone_Number', 'Last_Name') #Drop rows with missing values in specific columns 

dncMode = df['Do_Not_Contact'].mode()[0]
df['Do_Not_Contact'] = df['Do_Not_Contact'].fillna(dncMode)
#df['Do_Not_Contact'].isna().sum()
df['Last_Name']= df['Last_Name'].fillna('.')
df['Phone_Number'] = df['Phone_Number'].fillna('000')
df.isna().sum()

CustomerID           0
First_Name           0
Last_Name            0
Phone_Number         0
Address              0
Paying Customer      0
Do_Not_Contact       0
Not_Useful_Column    0
dtype: int64

## dealing with duplicates

In [33]:
#logic:there any duplicates in our data
df.duplicated().any()

np.True_

In [52]:
#how many Duplicate rows do we have?
df.duplicated().sum()

np.int64(0)

In [50]:
#what is the proportion of duplicate does in our data?
(df.duplicated().sum() / len(df)) * 100

np.float64(0.0)

In [53]:
#lets see the duplicated columns
df[df.duplicated(keep=False)] #View the duplicate rows (including First Occurrence)
#df[df.duplicated()] #View the duplicate rows (Excluding First Occurrence)

Empty DataFrame
Columns: [CustomerID, First_Name, Last_Name, Phone_Number, Address, Paying Customer, Do_Not_Contact, Not_Useful_Column]
Index: []

In [36]:
#REMOVING DUPLUICATE VALUES
df.drop_duplicates(inplace= True)

In [37]:
df.duplicated().any()

np.False_

In [38]:
df[df.duplicated(keep=False)] #View All Duplicate Rows
#df[df.duplicated()]

Empty DataFrame
Columns: [CustomerID, First_Name, Last_Name, Phone_Number, Address, Paying Customer, Do_Not_Contact, Not_Useful_Column]
Index: []

## Standardizing Variable values

In [91]:
for col in df.select_dtypes(include='object').columns:
    print(f"'{col}': {df[col].unique()}\n")

'First_Name': ['Frodo' 'Abed' 'Walter' 'Dwight' 'Jon' 'Ron' 'Jeff' 'Sherlock' 'Gandalf'
 'Peter' 'Samwise' 'Harry' 'Don' 'Leslie' 'Toby' 'Michael ' 'Clark'
 'Creed' 'Anakin']

'Last_Name': ['Baggins' 'Nadir' '/White' 'Schrute' 'Snow' 'Swanson' '  Winger' 'Holmes'
 nan 'Parker' 'Gamgee' 'Potter' 'Draper' 'Knope' 'Flenderson_' 'Weasley'
 'Scott' 'Kent' 'Braton' 'Skywalker']

'Phone_Number': ['123-545-5421' '123/643/9775' 7066950392 '123-543-2345' '876|678|3469'
 '304-762-2467' nan 'N/a']

'Address': ['123 Shire Lane, Shire' '93 West Main Street' '298 Drugs Driveway'
 '980 Paper Avenue, Pennsylvania, 18503' '123 Dragons Road'
 '768 City Parkway' '1209 South Street' '98 Clue Drive' '123 Middle Earth'
 '25th Main Street, New York' '612 Shire Lane, Shire'
 '2394 Hogwarts Avenue' '2039 Main Street' '343 City Parkway'
 '214 HR Avenue' '2395 Hogwarts Avenue' '121 Paper Avenue, Pennsylvania'
 '3498 Super Lane' 'N/a' '910 Tatooine Road, Tatooine']

'Paying Customer': ['Yes' 'No' 'N' 'Y' 'N/a']

'Do_Not_Contact': ['No' 'Yes' nan 'Y' 'N']

In [79]:
df['Paying Customer']= df['Paying Customer'].map( {'Yes': 'Yes',  
                                               'Y': 'Yes',
                                               'No': 'No',
                                               'N': 'No',
                                               'N/a':' '} )

df['Paying Customer']= df['Paying Customer'].fillna(df['Paying Customer'].mode()[0]) #fill missing variables
df['Paying Customer'].unique()

array(['Yes', 'No'], dtype=object)

In [80]:
df['Do_Not_Contact']= df['Do_Not_Contact'].map({'Yes':'Yes',
                                               'Y':'Yes',
                                               'No':'No',
                                               'N':'No',})
df['Do_Not_Contact'].unique()

array(['No', 'Yes'], dtype=object)

In [90]:
# Standardize only one value and leave others unchanged
df['Last_Name'] = df['Last_Name'].replace({'...Potter': 'Potter'})