### Day 9 work

In [3]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [4]:
df = pd.read_csv("C:\\Users\\User\\Desktop\\Python files\\data\\car-sales-extended.csv")
df.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [5]:
# Splitting the data
x = df.drop("Price", axis=1)
y = df["Price"]

x.shape, y.shape

((1000, 4), (1000,))

## Encode the data

### Key considerations in this process

Target variables should never be passed into transformers
y must come from the original DataFrame

ColumnTransformer.fit_transform() does not return a pandas DataFrame

It returns a NumPy array (or sparse matrix)
NumPy arrays do not have column names or .drop()

passing the target varialbe through the transfomer can cause the risk possiblity of its leakage

steps to follow (Correct Way to Structure This Pipeline): 
1. Separate features (x) and target(y) first
2. Define categorical columns
3. Build the transformer correctly
4. Transform x only
5. (Optional but Recommended) Convert Back to DataFrame
6. continue to fitting and training the model

In [6]:
#columns to transform
cat_cols= ['Make', 'Colour', 'Doors']

#transfomer 
transformer= ColumnTransformer( transformers=  [('one_hot', OneHotEncoder(sparse_output= False
                                                                ,handle_unknown='ignore'), cat_cols)],
                               remainder= "passthrough")
transformer;

In [7]:
t_x= transformer.fit_transform(x)
t_x;

In [8]:
t_x= pd.DataFrame(t_x)
t_x.head(10)

    0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   42652.0
6  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  163453.0
7  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   43120.0
8  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  130538.0
9  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   51029.0

In [9]:
# looking into how encoding is done
print(x['Make'].unique())

print(x['Colour'].unique())

print(x['Doors'].unique())

t_x.shape

['Honda' 'BMW' 'Toyota' 'Nissan']
['White' 'Blue' 'Red' 'Green' 'Black']
[4 5 3]

(1000, 13)

## Model Fitting

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [11]:
#split the data
x_train, x_test, y_train, y_test = train_test_split(t_x,y, test_size= 0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 13), (200, 13), (800,), (200,))

In [12]:
#train the model
model= RandomForestRegressor().fit(x_train, y_train)

## Model Tuning

Manual Model Tuning

In [13]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [14]:
# Checking the model perfomance on the training data
print(f"The accuracy score of this model in the training data is: {model.score(x_train, y_train)*100:.2f}%")

The accuracy score of this model in the training data is: 89.07%

In [15]:
#tesing the model on the test data
model.predict(x_test)
# Checking the model perfomance on the test data
print(f"The accuracy of this model on the test data is: {model.score(x_test, y_test)*100:.2f}%")

The accuracy of this model on the test data is: 34.40%

In [16]:
#manually checking the model's perfomance accross adjusted parameters

for i in range(100, 300, 15):
    model2 = RandomForestRegressor(n_estimators= i).fit(x_train, y_train)
    print(f"The accuracy score of our model with {i} n_estimatiors is:\
    {model2.score(x_test, y_test)*100:.2f}%")

The accuracy score of our model with 100 n_estimatiors is:    32.76%
The accuracy score of our model with 115 n_estimatiors is:    34.24%
The accuracy score of our model with 130 n_estimatiors is:    34.82%
The accuracy score of our model with 145 n_estimatiors is:    34.48%
The accuracy score of our model with 160 n_estimatiors is:    35.79%
The accuracy score of our model with 175 n_estimatiors is:    33.63%
The accuracy score of our model with 190 n_estimatiors is:    35.32%
The accuracy score of our model with 205 n_estimatiors is:    35.12%
The accuracy score of our model with 220 n_estimatiors is:    34.31%
The accuracy score of our model with 235 n_estimatiors is:    34.49%
The accuracy score of our model with 250 n_estimatiors is:    35.25%
The accuracy score of our model with 265 n_estimatiors is:    35.02%
The accuracy score of our model with 280 n_estimatiors is:    34.48%
The accuracy score of our model with 295 n_estimatiors is:    34.28%

## GridSearchCV

Automated Model Tuning

 GridSearchCV automates, standardizes, and statistically improves model tuning.
 It: 
 1. Tries all combinations of specified hyperparameters
 2. Uses cross-validation to evaluate each combination
 3. Selects the best-performing parameter set
 4. Returns a fully trained model using the optimal parameters

Problems with the manual model tuning, eg. using loops above

 1. Evaluates performance on a single train/test split
 2. Prone to overfitting
 3. Only tunes one parameter
 4. No ranking or reproducibility guarantees

When NOT to use GridSearchCV

 1. Very large parameter spaces
 2. Very large datasets
 3. Expensive models
 4. In those cases, use: RandomizedSearchCV

In [23]:
#Define the base model
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1 #n_jobs=-1 Controls how many CPU cores are used during training and prediction.(-1 means use all available processor cores.)
)
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': -1,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [18]:
#Step 2: Define the parameter grid
param_grid = {
    "n_estimators": [10, 25, 50, 75, 100],
    "max_depth": [None, 5, 10, 20],
    "min_samples_split": [2, 5, 10]
}

In [19]:
#Step 3: Create the GridSearchCV object
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring="r2",
    cv=5,
    n_jobs=-1,
    verbose=1
)

In [20]:
#Step 4: Fit GridSearchCV
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

GridSearchCV(cv=5, estimator=RandomForestRegressor(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10, 20],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [10, 25, 50, 75, 100]},
             scoring='r2', verbose=1)

In [21]:
#5. Accessing the results
#Best parameters
grid_search.best_params_
#Best cross-validated score
grid_search.best_score_
#Best trained model
best_model = grid_search.best_estimator_

In [22]:
#6. Evaluate on the test set (critical step)
test_r2 = best_model.score(x_test, y_test)
print(f"Test R²: {test_r2:.3f}")

Test R²: 0.434